import { LOGO_MONO } from '../logos.js'
import { brandName, brandSub, brandLogoMono, isDemo } from '../brand.js'
// v310 — Letra E número convivem no pino (Raphael: "coloca um numero tb, mas com opção de ocultar"). Regressão MINHA, introduzida na v301 e achada ao testar a v308: a linha era `(letra ? letraTxt : txt)` — a letra SUBSTITUÍA o número, então câmera, AP e keystone ficavam sem o nº que cruza com as tabelas, e a dica da legenda ("mesmo desenho — pontos 5, 14") não achava correspondência no desenho justamente nesses pontos. Agora os dois saem. Onde: a meia lua ocupa só a METADE DIREITA do viewBox, então o número vai na metade esquerda (x=6, fonte 9), que estava vazia — cabem sem disputar espaço. Nos demais tipos o número segue centralizado (x=12, fonte 10). O número obedece ao toggle "Nº dentro do pino"; a LETRA não obedece, de propósito: ela diz o que o ponto é, não é identificador. VERIFICADO: editor mostra "C+8", "C+9", "A+10"; no documento, com nº = 16 números + 3 letras, ocultando = 0 números e as 3 letras preservadas. Base: v309.
// v309 — QDL sem especificação + ORIGEM REAL dos cabos de rede (Raphael). (1) "O QDL não tem tamanho, não entra especificação, é meramente pra ilustrar o local dele na casa — já está na casa e geralmente é bem maior que 4x4". specDoPonto passou a devolver caixa "—" e cabo "—" pro sym 'quadro', IGNORANDO até um caixaTipo gravado: "4x4 no QDL" é dado sem sentido, não escolha de projeto (única exceção ao princípio "o cadastro manda" da v299, e por isso está comentada). Semente do demo limpa (tinha caixaTipo:"4x4" no QDL escrito à mão; o editor já não oferecia esse campo pra quadro). VERIFICADO: linha do QDL com CAIXA "—" e CABO "—"; resumo de caixas caiu de 4x4 ×3 pra ×2 — exatamente os 2 keypads de 4 teclas. (2) "Os cabos não saem do rack, saem de uma porta de algum equipamento que está no rack — patch panel, switch, dream machine — você precisa ver o que tem". A Tabela de Portas usava `dev = from?.name || 'Rack'`: o "equipamento de origem" era o NOME DO MARCADOR ("Rack CPD") e a porta um contador inventado. Agora olha o que EXISTE no rack (rackMarker.rackEquip, que já tinha code/name/u/função) e escolhe pelo tipo de cabo: uplink → ONT/Gateway; ap e câmera (PoE) → Switch; dados → Patch Panel. A porta segue sequencial e está documentada como PROPOSTA de patch, não medida. O trechoCond ("Rack → Cômodo") ficou intacto de propósito: conduíte é eletroduto, sai do rack fisicamente, não de porta. Base: v308.
// v308 — ALERTA DE ALTURA + "forro" fora do quantitativo (Raphael). (1) "Keystone parede média (1,10m) · 0,30 m" é erro de CLASSIFICAÇÃO e o app precisa alertar (Raphael). Causa: o TIPO é deduzido do NOME (classifyEle) e carrega a altura chumbada no rótulo, enquanto a altura real vem do DADO — ninguém conferia os dois, e o documento imprimia as duas alturas para o mesmo ponto. Nova alturaAfirmadaPeloTipo() mapeia sym→altura (keystone_baixo/alto/teto, tomada_*, ponto_som_*, ponto_energia_*, arandela_teto, ponto_luz) e alertaDoPonto passou a checar tipo×altura além de tipo×cabo. VERIFICADO fabricando o caso: ponto "Keystone teto CAT6" com altura baixa → "Keystone de teto (rede) está a 0,30 m — o tipo diz no teto. Corrija o tipo do ponto ou a altura." (2) "Caixa de embutir forro — 23 un" no Quantitativo de Material: forro não é caixa, é o lugar do ponto. O quantitativo tinha a PRÓPRIA contagem (4ª fonte) e não passou pelo conserto da v307. Nova ehCaixaDeEmbutir() no módulo, usada pelo resumo E pelo quantitativo; ambos varrem todos os pontos (keystone e som pedem 4x2 e ficam fora do isPontoEletrico). PENDENTE ACHADO: nos pontos de rede a LETRA (K/C/A) substitui o número dentro do pino — então câmera, AP e keystone ficam SEM o nº que cruza com as tabelas, e a dica "pontos 5, 14" da legenda não acha correspondência no desenho. Base: v307.
// v307 — TUDO EM A4 + abertura do Plano de Obra + início do lote 3. (1) A4 EM TODOS OS DOCUMENTOS (Raphael): Obra, Elétrica e Conduítes saíam em @page A3 LANDSCAPE — só o Completo era A4. Era a origem do aviso "Para impressão em A3" e da diferença de escala entre os documentos. A folha da parede segue A4 paisagem (é uma só, pra pregar). (2) Abertura do Plano de Obra REMOVIDA: título + aviso de A3 + legenda repetida antes de qualquer planta — a capa já diz o que é o documento e a legenda vem colada em cada planta. Agora ele abre direto na Planta Completa. (3) CAIXAS DE EMBUTIR — RESUMO agora puxa TODAS (Raphael): varria só eleMarks, e keystone e ponto de som ficam fora do ELE_SYMS_SET apesar de pedirem 4x2 — a lista de compra do eletricista saía CURTA. Agora varre todos os pontos e filtra o que é caixa de verdade (4x2/4x4/octogonal/caixa de piso); "forro" e "quadro" são lugar, não caixa. (4) CHECKLIST ELÉTRICO com mark check: era <ul> de bolinhas, que não se marca; virou caixa quadrada igual à do checklist do Plano de Obra. VERIFICADO: aviso de A3 ausente, Plano de Obra abrindo na Planta Completa, 6 caixas no checklist, resumo com 4x2 e 4x4. NOTA: o QDL aparece como 4x4 no resumo porque o marcador do DEMO tem caixaTipo:'4x4' gravado — override do cadastro, que o specDoPonto respeita de propósito (v299). Base: v306.
// v306 — TAMANHO DO PINO e toggle do número (Raphael, com os dois prints). A Planta de Pontos do Projeto Executivo usava pino de 24px e a "Planta Completa" do Plano de Obra usa 18px — e a planta do executivo ainda é MAIS ESTREITA, então o pino dominava o desenho. Não era o pino: era 33% maior numa planta menor. Igualado em 18px (nova const PIN_PX). O número acompanha sozinho, porque o SVG é viewBox 24 escalado por size. (2) Novo toggle "Nº dentro do pino" (Com nº / Só símbolo) no painel de opções: desligado, o pino vira só o símbolo. As letras K/C/A do ponto de rede NÃO somem — elas dizem o que é, não são ID. Novo estado showNumPin + _pinLabel(); registrado nas dependências do preview ao vivo. ARMADILHA DE ESCOPO que eu criei e corrigi: meu script trocou o rótulo dentro de drawPin, que é função de MÓDULO e não enxerga _pinLabel (estado do componente) — quebrou a geração com "ReferenceError: _pinLabel is not defined". Agora drawPin recebe `label` por parâmetro (default = nº do ponto) e os 6 chamadores, que vivem no componente, é que passam. VERIFICADO: pino 18px; toggle 13 números → 0, com as 3 letras preservadas. Base: v305.
// v305 — LEGENDA: "um de cada" (Raphael, com print). Ela mostrava linhas GÊMEAS — "Interruptor 3 teclas ×3" e "Interruptor 3 teclas ×4" logo abaixo, idênticas. Erro meu: apliquei "não fundir itens NUNCA" (v296) na legenda também, então ela agrupava por m.name — e dois produtos diferentes com a mesma função desenham igual e escrevem igual. A regra vale nas TABELAS, onde o item é o assunto; na LEGENDA o assunto é o símbolo. Agora a chave é o que a linha MOSTRA: função + tipo do pino + preenchimento + nº de traços + letra + família do cabo. VERIFICADO fabricando o caso real (renomeei 1 dos 2 "Keypad 4 teclas" pra "Keypad Premium Zigbee 4 Botões Prata"): legenda deu UMA linha "Interruptor 4 teclas ×2" e a tabela mestra manteve os DOIS produtos separados na coluna Equip. — funde onde deve, separa onde deve; soma 16 = 16 pontos. (2) Texto do ponto de rede passou a dizer o que a LETRA diz: três linhas escreviam "Keystone de teto (rede)" e só se distinguiam pelo A/C/K no desenho; agora sai "… — câmera" / "… — access point" (não acrescenta quando o texto já diz, pra não virar "Câmera externa 4MP — câmera"). Base: v304.
// v304 — LOTE 2 da revisão: estrutura do PROJETO EXECUTIVO. (1) MERGE: a tabela "Automação — Interruptores, Keypads e Módulos" foi ELIMINADA e a "Posição e Altura dos Pontos" virou a MESTRA. Elas eram as duas por cômodo, com as mesmas colunas — a mestra já dizia tudo. A única coluna exclusiva da Automação migrou: "Equip." (o produto do catálogo). Mestra agora: PONTO · ID · ITEM · EQUIP. · LOCAL · ALTURA · CAIXA · CABO, onde ITEM = a função ("Interruptor 4 teclas") e EQUIP. = o produto ("Keypad 4 teclas"); quando os dois são iguais, EQUIP. mostra "—" em vez de repetir. Isso também resolve um buraco: se a mestra tivesse sumido em vez da Automação, som/câmera/AP/sensor ficariam sem altura e sem caixa no documento inteiro (a tabela de Som só tem ambiente e cabo). (2) Wi-Fi passou pra ANTES da Planta Elétrica. (3) Tabela "Observações dos Pontos" removida — a observação já viaja junto do ponto nas tabelas por cômodo; a seção virou só "Fotos do Diário de Obra". CONFLITO RESOLVIDO: a msg dizia "9 vira lista completa de peças" e depois "Equipamentos por Cômodo e Lista de Peças pode manter como está" — segui a segunda (mais recente e nomeando a seção pelo título inteiro) e a seção ficou intacta. VERIFICADO no doc: Automação ausente, mestra com as 8 colunas, Wi-Fi (3) antes da Elétrica (4). Base: v303.
// v303 — LOTE 1 de 5 da revisão dos documentos (Raphael). (1) CAPA DO CONDUÍTES: o documento se apresentava como OUTRO — "DOCUMENTO TÉCNICO · PROJETO EXECUTIVO / Projeto Executivo de Automação". Causa: a capa tinha ramo para elétrica e obra, mas NENHUM para 'conduites', então caía no else do executivo. Novo _cond: "DOCUMENTO TÉCNICO · CONDUÍTES / Conduítes e Infraestrutura / Caminho dos eletrodutos · Bitolas · Caixas de passagem". (2) ELÉTRICA: saiu o Wi-Fi do título e o "Mapa de calor Wi-Fi" do subtítulo — agora é sempre "DOCUMENTO TÉCNICO · ELÉTRICA / Planta Elétrica". A flag _temWifi existia só pra isso e foi removida (sem código morto). (3) ORDEM dos documentos no app = ordem da obra acontecendo: Plano de Obra → Projeto Executivo → Elétrica → Conduítes (o Plano de Instalação entra no lote 5). REGRA DA CAIXA CONFIRMADA pelo Raphael: acima de 3 teclas = 4x4 (mantém a v297; a msg dele dizia "só 6 teclas é 4x4" e eu perguntei antes de mexer). VERIFICADO no preview: as 4 abas na ordem nova; capa do Conduítes e da Elétrica corretas. Base: v302.
// v302 — Coluna ABNT fora da legenda (Raphael). Com os símbolos da elétrica e os pinos falando a mesma língua (v301), ela virou espelho: o interruptor saía como círculo vermelho com traços nas DUAS colunas. Legenda agora: PINO · O QUE É · ALTURA · CABO · QTD. Junto, o teste de "mesmo desenho" foi corrigido — ele media corDoPino + mount + altura + família + símbolo ABNT, ou seja, a cor VELHA (que não desenha mais nada) e uma coluna que deixou de existir. Agora a assinatura é exatamente o que o pino desenha: tipo (forma+cor) + preenchimento (altura) + nº de traços (teclas) + letra da meia lua. Resultado mais correto que antes: interruptor de 2 × 4 teclas não avisa mais (os traços já separam) e o aviso sobra só nos dois módulos, que são losangos pretos genuinamente idênticos. VERIFICADO: colunas sem ABNT, 2 avisos (os certos), 9 linhas. Base: v301.
// v301 — IDIOMA NOVO DOS PINOS (Raphael): forma+cor = O QUE É · preenchimento = ALTURA · traços = nº de teclas. Antes a cor era "categoria" (6 cores), a forma era o plano de montagem e a altura era um tracinho de 2px — ilegível impresso. Agora: interruptor círculo vermelho com N traços (1 traço = 1 tecla, 6 = 6); tomada seta azul; ponto de rede meia lua amarela com LETRA (K keystone · C câmera · A access point — a letra substitui o selo "R", que só repetia o que a cor amarela já diz); ponto de som quadrado laranja; ponto de elétrica losango preto (sensor, módulo, cortina); QDL à parte (retângulo preto com barramento — é origem, não ponto). Preenchimento: vazio 0,30 · metade horizontal 1,10 · metade vertical 1,80 · cheio teto · X piso — recortado pela própria forma (clipPath), nunca vaza. Número do ponto com contorno branco (paint-order) pra ficar legível sobre qualquer preenchimento. Novo motor pinNovoSVG; pinShapeSVG delega quando recebe o marcador e mantém o desenho velho sem ele (legenda dos modelos legados segue coerente). Selo E/S/R encolhido de 12-13px para 9px ("está tomando muito espaço"): 8 ocorrências. VERIFICADO no doc: AP→meia lua "A", câmera→meia lua "C", som→quadrado, interruptor 2 teclas→círculo 2 traços, 4 teclas→4 traços, módulo/sensor→losango, QDL→retângulo; preenchimentos lendo certo. Base: v300.
// v300 — "Sensor mmW é elétrica" (Raphael) — e isso fechou os 6 pontos de CABO divergente que estavam pendentes. (1) Erro MEU corrigido: specDoPonto dava 'CAT6' pro sensor (chute meu na v297); agora é 2×2,5mm² (F+N) — dispositivo Zigbee alimentado, igual ao módulo. (2) O sensor não era conferido por NINGUÉM: classifyEle só conhece ponto elétrico e devolve null pra sensor, então familiaExigidaPeloTipo passava batido. Ganhou fallback por nome (sensor/mmWave e cortina/módulo → elétrica), e agora sensor com cabo de rede gera alerta. (3) Semente do demo corrigida (sensor 'dados'→'eletrica'). (4) QUARTA derivação ad-hoc de cabo eliminada: a tabela "Itens no Teto" calculava o cabo por conta própria ('Zigbee · sem cabo (mesh)' / 'CAT6 (PoE) · trace na planta' / '—') e destoava do resto — o sensor saía "—" e o AP saía diferente das outras tabelas. Agora usa specDoPonto e só acrescenta a metragem quando há cabo traçado. VERIFICADO por varredura de todas as tabelas: 20 pontos, 0 divergências de cabo E de caixa (era 6 no cabo); sensor = 2×2,5mm² (F+N) em todas; AP = CAT6 PoE em todas; sensor com selo E. Base: v299.
// v299 — CORREÇÃO DE RUMO: a regra do keypad é CONFERÊNCIA, não camisa de força. Na v298 eu impus a família por cima do cadastro (familiaFixaDoPonto vencia m.cableType, e o campo do editor ficava travado com cadeado). Errado: "quem vai definir isso é Tipo do ponto e Cabo que chega neste ponto dentro do editor, mas se alguém marcar uma tomada no teto com cabo de rede é um alerta pois não tem como" (Raphael). Agora: familiaDoPontoTipo volta a ser m.cableType || guessCableType (a escolha de quem cadastra MANDA e nunca é sobrescrita); o dropdown do editor voltou livre, com "✨ Automático → Elétrica" sugerindo certo. Em vez de travar, o app CONFERE: nova familiaExigidaPeloTipo() diz qual família o tipo exige fisicamente (interruptor/tomada/ponto de energia/luz/arandela → elétrica; keystone → rede; ponto de som → som; demais → null = escolha livre) e alertaDoPonto() devolve o aviso quando o cabo escolhido não bate. O aviso sai em vermelho logo abaixo do campo, no painel do ponto. VERIFICADO ao vivo: keypad com cabo trocado pra Dados → "Interruptor 4 teclas não recebe cabo de rede — é ponto de elétrica.", com a escolha PRESERVADA no campo. Base: v298.
// v298 — "Keypad NUNCA é rede, é elétrica... keystone é" (Raphael). Vira REGRA DURA, não default: familiaFixaDoPonto() impõe elétrica para interruptor/keypad e módulo cabeceira, e rede para keystone — VENCENDO o m.cableType gravado. Motivo: depois da v297 o keypad declarava DUAS famílias no mesmo ponto — selo R (rede) na planta e cabo 3×2,5mm² (F+N+T) (elétrica) na tabela. O guessCableType já classificava certo (keypad→eletrica); o furo é que ele só era consultado quando não havia cableType, e a semente do demo cravava 'dados'. Agora: guessCableType movido pro escopo do MÓDULO (é função pura) junto das outras regras; nova familiaDoPontoTipo() é a fonte única e os 12 call sites que repetiam `m.cableType||guessCableType(m,m)` passaram a chamá-la; demo seed corrigido (4 keypads 'dados'→'eletrica'). EDITOR: o campo "Cabo que chega neste ponto" fica TRAVADO (com cadeado) em keypad/keystone — deixar escolher e o documento imprimir outra coisa seria mentir pra quem cadastra; nos demais segue dropdown livre. VERIFICADO: keypads com selo E; 0 divergências de caixa em 20 pontos; KP-01/03 (4 teclas)=4x4 e KP-02/04 (2 teclas)=4x2. PENDENTE: Sensor mmW sai com selo R — guessCableType diz 'eletrica', a semente diz 'dados' e specDoPonto (que EU escrevi) diz 'CAT6': três respostas, aguardando a decisão do Raphael. Base: v297.
// v297 — PLANO DE OBRA: caixa e cabo agora têm FONTE ÚNICA (specDoPonto), e a tabela do cômodo finalmente responde o que o documento existe pra responder. O Plano de Obra serve pro peão saber ONDE deixar a ponta e QUE cabo é (Raphael) — e falhava nisso em dois níveis: (a) a tabela "Posição e Altura", a única organizada por CÔMODO (que é como ele trabalha), não tinha caixa NEM cabo — mandava procurar em 2 outras seções organizadas por SISTEMA; (b) onde o cabo aparecia, o documento se CONTRADIZIA: o ponto KP-04 (keypad 2 teclas) saía como "4×4 + NEUTRO · 3×2,5mm² (F+N+T)" na Automação e "4x2 · 2×1,5mm² (retorno)" na Planta Elétrica, no MESMO documento. Causa: TRÊS tabelas hardcoded independentes — caboDe/caixaDe (gerador), caixaPadrao (módulo), fiosDe (renderizador). Unificadas em specDoPonto(m), única fonte; os 3 consumidores agora chamam ela. REGRAS: caixa do keypad = 4x2 até 3 teclas, 4x4 acima (regra do Raphael; caixaPadrao já fazia certo, o gerador é que cravava 4×4 pra todos); cabo do keypad = SEMPRE 3×2,5mm² (F+N+T), porque keypad Zigbee é dispositivo ALIMENTADO e não leva "retorno" — a Planta Elétrica o tratava como interruptor burro, contra a convenção RARO já escrita no prompt da IA ("Keypads SEMPRE fase+neutro 2,5mm²"). classifyEle passou a devolver `teclas`. A tabela do cômodo ganhou CAIXA + CABO e passou a exibir a função (não o nome comercial). VERIFICADO por varredura de TODAS as tabelas: KP-01 (4 teclas) = 4x4 e KP-02 (2 teclas) = 4x2, ambos 3×2,5mm² (F+N+T), idênticos em 4 seções; 0 divergências de caixa em 20 pontos. PENDENTE: 6 pontos ainda divergem no texto da coluna CABO entre seções (família "Som" × spec "2×1,5mm²"; "CAT6 PoE" × "CAT6 (PoE) · trace na planta"; alguns "—"). Base: v296.
// v296 — REGRA DO RAPHAEL: "não vamos fundir itens NUNCA". A v295 agrupava a legenda por FUNÇÃO e isso achatava itens distintos ("Módulo de cortina" + "Módulo de iluminação 4 canais" → "Módulo ×3"). Separado o que agrupa do que aparece escrito: a CHAVE da dedup voltou a ser o ITEM (nome do catálogo + altura + local + cabo) — dois produtos distintos são sempre duas linhas, mesmo desenhando igual; e o TEXTO continua sendo a função (funcaoDoPonto). O fallback de funcaoDoPonto deixou de ser equipType (categoria genérica "Módulo", que era a causa do achatamento) e passou a ser o NOME do item; classifyEle segue descascando o nome comercial onde sabe ("Keypad Premium Zigbee 2 Botões Prata" → "Interruptor 2 teclas"). VERIFICADO no doc: 9 linhas e a SOMA das quantidades = 16 = exatamente os 16 marcadores da planta (nada fundido, nada perdido); módulos separados de novo; aviso "mesmo desenho" voltou só neles (desenham igual e não têm ABNT), e segue ausente nos interruptores (ABNT separa). Base: v295.
// v295 — LEGENDA OPUS enxuta (pedido do Raphael): (1) SAIU a coluna CÓDIGO e SAIU o bloco "pino explicado" (as 5 linhas "A cor diz o que é / A forma diz onde instalar / ..."). Ficou: PINO · ABNT · O QUE É · ALTURA · CABO · QTD. (2) "O QUE É" agora diz FUNÇÃO, não modelo comercial: nada de "Keypad Premium Zigbee 2 Botões Prata" — diz "Interruptor 2 teclas". Nova funcaoDoPonto() = classifyEle().tipo (função normalizada) || equipType() (categoria genérica: Câmera, Som, Wi-Fi, Módulo). A DEDUP passou a agrupar por FUNÇÃO (era por nome do catálogo): 2 modelos diferentes que fazem a mesma coisa e desenham igual viram 1 linha. CONSEQUÊNCIA: "Módulo de cortina" + "Módulo de iluminação 4 canais" viraram uma linha "Módulo ×3" (equipType não distingue) — conferir se precisa separar. (3) ELE_TYPE_INFO e classifyEle: "Keypad N teclas" → "Interruptor N teclas" (palavra da prancha). (4) TOMADA DE TETO × PONTO DE ELÉTRICA NO TETO agora se diferenciam: ponto de energia/força ganhou cabeça REDONDA (quadrado+círculo) contra a seta da tomada (quadrado+triângulo) — é a mesma regra da prancha, que separa "TOMADA FORÇA ALTA" (círculo) das tomadas comuns (seta). (5) O teste de ambiguidade passou a considerar o símbolo ABNT: se o ABNT já separa (2 × 4 traços), não sai aviso. VERIFICADO: 8 linhas, 0 avisos (era 4), colunas sem Código, 0 anatomia. Base: v294.
// v294 — SÍMBOLOS ELÉTRICOS REDESENHADOS no padrão da prancha da RARO (foto do quadro "LEGENDA DE PONTOS DE ELÉTRICA"). VALE TODOS OS MODELOS (ELE_SYMBOLS é compartilhado). Gramática, agora explícita no topo do arquivo: haste horizontal (parede) + cabeça; PREENCHIMENTO = ALTURA (vazado 0,30 · metade 1,10 · cheio 1,80 — substitui o "tracinho" de 2px que era invisível impresso); piso/teto saem da parede e viram a cabeça DENTRO DE UM QUADRADO (piso vazado, teto cheio); COR = sistema (vermelho = comando/iluminação, azul = tomada/rede/som). Helpers _haste/_seta/_caixa/_letra/_arandela/_keypad. O S1/S2/S4/S6 que existia era invenção nossa, não norma — a prancha real não usa S nenhum. KEYPAD: traços radiais = nº de teclas. 3W/4W FORA: são topologia de fiação e a RARO não puxa paralelo — dois keypads na mesma luz é cena Zigbee (resposta do Raphael). Por isso o classifyEle parou de tratar "paralelo/three-way/hotel" como topologia: só o nº de teclas do nome manda, e os rótulos viraram "2 teclas"/"4 teclas" em vez de S2/S4. Chaves interruptor_paralelo/intermediario mantidas (= 2 e 3 teclas) pra não quebrar projeto salvo, agora documentadas como legado. Fora da prancha (QDL, prumada, módulo cabeceira, keypad 4/6, ponto de luz, som teto/piso, keystone teto) desenhados no mesmo idioma. Telefone/interfone/antena/cigarra/campainha NÃO entram (a RARO não faz). VERIFICADO no doc: tomadas vazado→metade→cheio, piso/teto no quadrado, keypads com traços, rótulos "2 teclas"/"4 teclas". Base: v293.
// v293 — (1) LEGENDA OPUS ganhou coluna ABNT: o próprio símbolo NBR 5444 (não só a sigla) que a Planta Elétrica já usa, costurando as duas plantas — é a norma que responde "quantas teclas" (S2 = 2, S4 = 4), então NÃO inventamos bolinha/tracinho (seriam 2px num pino de 22px que já tem número dentro, e só resolveriam a família keypad: COR×MOD4 colidem sem ter tecla pra contar). Traz de volta a ponte que a "Legenda mestre NBR" fazia e que a legenda nova tinha aposentado. (2) "Resumo por Item (tipos únicos)" não sai mais no OPUS — a legenda embaixo da planta virou a mesma tabela (mesma dedup, e ainda com ABNT + desempate); os outros modelos seguem com ela. (3) BUG ABNT CORRIGIDO — VALE TODOS OS MODELOS, achado pela coluna nova: classifyEle mandava TODO keypad de 3+ teclas pra interruptor_intermediario, que DESENHA S3, mas escrevia a sigla S${nb} — o mesmo ponto dizia S3 e S4. E interruptor_4 (desenha S4) era inalcançável. Pior: caixaPadrao() só devolve 4x4 para interruptor_6/interruptor_4, então keypad de 4 teclas entrava na coluna CAIXA e no QUANTITATIVO DE CAIXAS como 4x2. Agora 4-5 teclas → interruptor_4/S4 (sem glifo S5: o 5 usa S4 e o "tipo" carrega o nº real), 3 → S3. CONSEQUÊNCIA A CONFERIR: keypad de 4 teclas passa a especificar caixa 4x4. VERIFICADO: "Keypad 4 teclas → desenho S4, sigla S4". Base: v292.
// v292 — LEGENDA OPUS, ajustes: (1) o CÓDIGO SAIU DA PLANTA (poluía com muitos itens — pedido do Raphael). Sem ele, tipos que DESENHAM IGUAL voltariam a ficar ambíguos, então o desempate migrou pra legenda e só nas linhas que colidem de fato: quando 2+ tipos têm o mesmo (cor+forma+altura+selo), a linha diz "mesmo desenho de outro item — pontos 5, 14". Desenho único não ganha nada → a coluna não incha em projeto grande. No demo: 4 de 9 linhas (KP2/KP4 e COR/MOD4). O código continua na coluna da legenda (referência do catálogo), só não vai mais no desenho. (2) Pino explicado corrigido: dizia "o código diz qual item" — viraria mentira sem o código na planta; agora aponta o nº do ponto. (3) BUG DE COR CORRIGIDO (existia desde o "Resumo por item", herdado ao copiar): a planta pinta com catColorOf(m) || EQUIP_STYLE, mas o símbolo da legenda caía num cinza fixo #64748B quando catColorOf dava null → o MESMO ponto saía cinza na legenda e índigo #6366F1 na planta ("Módulo de cortina"/"Módulo de iluminação"), quebrando a única promessa da legenda. Nova função corDoPino() é fonte única. VERIFICADO no doc: 0 etiquetas na planta e na parede, 9 linhas, 0 divergências de cor legenda×planta, cinza fixo eliminado. Base: v291.
// v291 — LEGENDA NOVA, só no modelo OPUS (nova/antiga/fable intactos: os 3 pontos de entrada são gates de igualdade em 'opus'). A legenda abstrata cor/forma/selo obrigava o peão a 3 consultas e a combinar de cabeça; agora a legenda É a lista do que existe NESTA planta, um símbolo por TIPO (16 pontos → 9 linhas; 4 caixas de som = 1 linha ×4), mais o "pino explicado" no lugar do parágrafo de 60 palavras. Cada linha traz o CÓDIGO DO TIPO (KP2/KP4/CAM4/SPEMB), que resolve o empate real de desenhos idênticos — Keypad 2 e 4 teclas são o mesmo círculo verde + R. O código vem do CATÁLOGO indexado por nome (novo tipoCodigo()/_codeByName): o marcador só tem a etiqueta da INSTÂNCIA (m.code="KP-01"), que não sabe o tipo e, usada como chave, gerava 1 linha por ponto. Fallback = prefixo da instância (QDL-01→QDL). O mesmo código vai colado embaixo de cada pino na planta de pontos e na folha da parede (não cabe DENTRO: pino de 22px não segura "SENMMW"). VERIFICADO no doc gerado: 9 linhas, códigos APW6/SPEMB/CAM4/KP2/KP4/COR/MOD4/QDL/SENMMW, 16 etiquetas na planta cujas 9 únicas batem 1:1 com as linhas; folha da parede idem. Base: v290.
// v290 — Selos de cabo E/R/S GRUDADOS também nas TABELAS. A v289 só tinha corrigido as plantas (offset -3/-3); nas tabelas o selo era elemento IRMÃO do pino com gap:4-5px — por construção afastado. Agora os 3 renderers de tabela (pin() da tabela por cômodo, simb() de "Posição e Altura" e de "Resumo por item") usam wrapper position:relative com o selo em position:absolute;top:-3px;right:-3px, igual à planta. VERIFICADO no preview ao vivo: selos grudados dentro de tabela 0 → 39; total 44 → 83 (44 planta + 39 tabela); confirmado no zoom (antes "△  S" lado a lado, agora S no canto do △). Base: v289.
// v289 — (1) SENHA 123 nas ações que mexem no projeto: "Gerar/Regerar com IA" (novo) + Recomeçar, Apagar projeto e Limpar (a senha era 456, virou 123 — confirmarComSenha/SENHA_ACAO). (2) Selos de cabo E/R/S agora GRUDADOS no item (offset -6/-7 → -3/-3, sobrepõe o canto do pino) em todas as plantas. VERIFICADO: 44 selos na posição nova, 0 na antiga. (3) Só o modelo OPUS fica visível: execVersao default 'opus' (inclusive no demo) e o seletor "Estilo" só aparece se os legados forem reabilitados em Admins → "Modelos de documento" (flag localStorage raro_modelos_legados, botão protegido por PIN). Novo/Clássico/Fable continuam no código, só ocultos. Base: v288.
// v288 — PROJETO EXECUTIVO (ocultar): agora TODO tópico dos dois documentos tem chave própria (Premissas, Planta de pontos, Posição/altura, Resumo por item, Automação, Som, Segurança, Rack, Planta elétrica, Wi-Fi, Teto, Cabeamento/conduítes, Equipamentos/peças, Gráficos, Observações + Obra: elétrica, quantitativo, cabeamento, checklists). Seletor refeito por TÓPICO com 2 granularidades: "tópico" (tira título+planta+tabela) e "só tabela" (mantém a planta) nos tópicos que têm planta+tabela (Rack, Elétrica). Master "Ocultar tudo". VERIFICADO no render: ocultar Wi-Fi (tópico) some tudo; "só tabela" da Elétrica mantém a planta e tira as tabelas. Vale todos os modelos. Base: v287.
// v287 — PROJETO EXECUTIVO: novo MODELO "Opus" (selecionável ao gerar; novo/clássico/fable INTACTOS). Acabamento máximo + aproveitamento de folha: (1) tema navy profundo + dourado quente, tabelas com fio dourado; (2) CAPA com faixa de escopo (pontos·cômodos·sistemas·cabeamento) preenchendo o vazio; (3) planta de cabeamento/conduíte COMPACTA + tabela na MESMA folha (acabou o desperdício de ~75% da página, sem "visão completa" redundante); (4) colunas 100% vazias ("—"/"—m") somem das tabelas; (5) folha da parede numa página só. VERIFICADO renderizando o PDF (Chrome headless + poppler): doc do demo caiu de ~muitas pra 21 páginas, capa com 16 pontos·8 cômodos·3 sistemas, planta+tabela juntas. Base: v286.
// v286 — PROJETO EXECUTIVO: (1) seletor de ocultar tabelas UNIFICADO num painel só ("Ocultar tabelas do documento") — acabou a confusão "Seções do Plano de Obra" vs "Tabelas do documento"; 12 chips com rótulos claros + "Todas as tabelas". VERIFICADO no preview (toggle Automação 1→0). (2) QUEBRAS DE PÁGINA INTELIGENTES (só impressão): título nunca fica órfão (break-after:avoid em h2/h3/.ex-amb), planta/figura não parte no meio (break-inside:avoid em .ex-plant e nos divs de planta com padding-bottom), linha de tabela não corta, cabeçalho de tabela repete. Conferir no PDF (preview é rolagem, não pagina). Base: v285.
// v285 — PROJETO EXECUTIVO #5 (produção): DESDUPLICAÇÃO do documento Completo/Executivo. Era _full + _obra + _ele concatenados, repetindo tudo (Planta Elétrica saía 3×, Posição e Altura 2×). Agora: (1) _ele não entra no Completo (o corpo já tem a elétrica); (2) a obra entra como ANEXO ENXUTO (buildExecHtml ganhou flag embedded) — pula planta de pontos, posição/altura e a planta elétrica que o corpo já traz, mantendo só o que é exclusivo de obra (caixas/alimentação, quantitativo, cabeamento por família, checklists, notas). VERIFICADO no render: Planta Elétrica 1×, Posição e Altura 1×, Planta de Pontos 1×, folha da parede 1×. Plano de Obra avulso continua completo. Base: v284.
// v284 — PROJETO EXECUTIVO (produção): (a) OCULTAR TABELAS agora funciona de verdade — a cópia da "Posição e Altura" no _obra (obraPosAlt) não passava pelo gate; agora respeita secOff('pos_altura'). VERIFICADO no render: esconder → 2 caem pra 0. (b) Folha da parede (#4) some a duplicata: buildWallPage() único, montado por último (depois de _full+_obra+_ele), 1 folha sozinha. VERIFICADO: 1×. PENDENTE #5: Completo ainda repete "Posição e Altura" (_full + _obra) e força quebras — falta compactar/deduplicar pra ficar elegante. Base: v283.
// v283 — PROJETO EXECUTIVO (produção): (#4) ÚLTIMA FOLHA nova nos docs Executivo e Obra — "Planta Completa · Mapa de Pontos · para a obra": planta no maior tamanho (A4 paisagem, @page wallpage), só planta + legenda, pra pregar na parede. Ancoragem à prova: caixa com aspect-ratio da imagem + object-fit:fill → pinos em % ficam exatos sobre o desenho em qualquer tamanho. (#3) Seletor de tabelas ampliado: agora dá pra ocultar uma a uma (Automação, Som, Segurança, Rack/Portas, Teto, Posição e Altura, Resumo por item) ou "Todas as tabelas". Compila; conferir no PDF (preview ao vivo estava fora). PENDENTE: #5 (compactar plantas + juntar tabelas na mesma folha). Base: v282.
// v282 — DEMO/MARCA D'ÁGUA: conferido que os 6 documentos saem com "DEMONSTRAÇÃO" no demo — proposta/contrato/apresentação embutem demoWatermark() direto; projeto executivo/plano de obra/planta elétrica saem via buildFullHtml (marca fora do branch de modo, vale Completo/Obra/Elétrica) — verificado 5× no render do executivo. Fechado um vão latente: wrapExecDoc (abrir doc pela lista de Orçamentos) não injetava a marca; agora injeta demoWatermark() (só no demo; produção continua sem marca). Base: v281.
// v281 — PROJETO EXECUTIVO #6 (produção): causa dos "pontos fora" achada — markersFromProposal jogava itens de cômodos SEM posição numa grade que varria a folha inteira (x4-96/y6-94), caindo na moldura branca de plantas que não preenchem o quadro. Correção: (1) computeContentBox detecta a área DESENHADA (bbox não-branca) da planta no onLoad; (2) a grade de fallback e o clamp agora ficam DENTRO dessa área; (3) botão "Encaixar na planta" no editor reencaixa pontos já espalhados (remap proporcional, desfazível). Compila; remap não dá pra ver no demo (planta demo preenche o quadro todo — computeContentBox retorna null, caminho correto). Testar no projeto real. Base: v280.
// v280 — DEMO: 2 conduítes fictícios (C1 dados, C2 elétrica) na planta demo pra exibir/validar o #5. VERIFICADO no render: rótulo do conduíte cai longe dos pinos (C1 no ponto a ~11 de dist do pino mais próximo), 100% opaco. Seed demo v4→v5 (reseed limpo). Produção intacta. Base: v279.
// v279 — PROJETO EXECUTIVO: (#2) legenda COMPLETA de símbolos elétricos ABNT NBR 5444 na Planta Elétrica — todos os símbolos agrupados (Tomadas, Interruptores, Iluminação, Energia, Som, Rede, Infra) com significado (abntLegendaCompleta). VERIFICADO no render. (#5) rótulo do conduíte (C1/C2...) agora vai no ponto do trecho MAIS LONGE de qualquer pino (não carimba em cima de item) e 100% opaco com contorno branco, nas 3 plantas do documento. Compila; sem conduíte semeado no demo pra conferir no render (lógica direta). Vale produção e demo. Base: v278.
// v278 — PROJETO EXECUTIVO: "IDs nas tabelas" agora vale para TODAS as tabelas do documento (não só Posição e Altura) — o helper T() remove a coluna cujo cabeçalho é "ID" (cabeçalho + célula de cada linha), então automação/segurança/som/teto/elétrica/conduítes/plano de obra também respeitam o toggle. VERIFICADO no preview: 25 cabeçalhos ID → 0, colunas alinhadas. Vale produção e demo. Base: v277.
// v277 — PROJETO EXECUTIVO (tabelas): (1) nova tabela "Resumo por Item (tipos únicos)" — cada tipo de ponto aparece 1x com a quantidade (×N), serve de legenda; hideável. (2) Seletor de tabelas no painel "Opções do documento": grupo "Tabelas do documento" com chip "Todas as tabelas" (master) + chips individuais (Posição e Altura, Resumo por item), além das seções do Plano de Obra já existentes. (3) Toggle "IDs nas tabelas" (showIdsTbl) esconde a coluna de ID na tabela Posição e Altura. VERIFICADO no preview (build + render). Pendente: estender ocultar-ID às tabelas de IA (som/automação/etc.). Base: v276.
// v276 — SEGURANÇA: logout automático após 30 min de inatividade (mouse/teclado/toque/scroll zeram o cronômetro; checa a cada 30s). Vale para produção e demo. useEffect em App.jsx. Base para as próximas mudanças do Projeto Executivo (legenda, elétrica, ocultar tabelas, anti-sobreposição, retrato) que exigem seu ciclo de teste.
// v275 — DEMO: gate de acesso em /demo — pede usuário/senha (raro / @raro2026) antes de abrir a demonstração (trava LEVE client-side, não é auth real; senha fica no bundle). Aprovação fica em localStorage (raro_demo_auth); "Sair" limpa e exige o gate de novo. Componente DemoGate no App.jsx. PRODUÇÃO INTACTA.
// v274 — DEMO (só demo; produção intacta): (1) LEITURA demo isolada — all() em supabase.js agora lê do estado demo (localStorage), não do Supabase real; corrige catálogo e estoque que "sumiam" segundos após aparecer e o modal "Categoria faltando no catálogo". (2) Catálogo/planta demo alinhados à taxonomia oficial (Segurança/Redes/Sonorização/Automação) e catálogo demo com margem 10% (venda = custo × 1,10). (3) Aba "Acerto entre sócios" escondida no demo (CaixaRaro). (4) Log de auditoria escondido no demo: botão "Ver log" (Stock) e aba "Log de auditoria" (Reports); getStockLog/getAuditLog retornam [] no demo. (5) Dois diários de obra fictícios no projeto demo. Seed demo v3→v4 para forçar reseed limpo.
// v273 — DEMO: modelo/estilo do documento FIXO em Fable, sem escolha, nos 4 documentos: contrato, proposta, apresentação comercial e projeto executivo (seletores escondidos + default fable quando isDemo). PRODUÇÃO INTACTA: fora da demo, os seletores e defaults originais (novo/v2/nova) seguem iguais. Só o demo mudou.
// v266 — RESET DE SENHA (so admin dispara). Na tela Usuarios, cada linha ganha botao de chave (ti-key) visivel SO se currentUser.role==='admin', entre editar e excluir, protegido por PIN. Admin clica, confirma, e o Supabase envia e-mail de recuperacao pra pessoa (dispararResetSenha -> resetPasswordForEmail). SEGURANCA: admin NAO ve nem define a senha alheia (Supabase nao permite, bcrypt); ele so destrava, a pessoa cria a nova. CICLO COMPLETO: quando a pessoa clica no link do e-mail e volta ao RARO, o Login detecta (evento PASSWORD_RECOVERY do onAuthStateChange, ou hash type=recovery na URL) e mostra tela 'Crie sua nova senha' (definirNovaSenha -> updateUser); apos salvar, resolve sessao e entra. Funcoes novas no supabase.js: dispararResetSenha, definirNovaSenha. Fontes: supabase.com/docs/reference/javascript/auth-resetpasswordforemail, .../auth-onauthstatechange, .../auth-updateuser. Base: v265.

export default function Sidebar({ active, onNav, counts, user, onLogout, onAreaClientes }) {
  const item = (id, icon, label, badge, badgeCls='warn') => (
    <div className={`sb-item${active===id?' active':''}`} onClick={()=>onNav(id)}>
      <i className={`ti ti-${icon}`} aria-hidden />
      <span className="sb-label">{label}</span>
      {badge>0 && <span className={`sb-badge ${badgeCls}`}>{badge}</span>}
    </div>
  )
  return (
    <div className="sidebar">
      {/* Logo — hidden on mobile */}
      <div className="sb-logo">
        <img src={brandLogoMono()} alt={brandName()} style={{height:46,width:46,borderRadius:8,objectFit:'contain'}} />
        <div>
          <div className="sb-brand">{brandName()}</div>
          <div className="sb-sub">{brandSub()}</div>
        </div>
      </div>

      <div className="sb-section">Menu</div>
      {item('dashboard','layout-dashboard','Dashboard')}
      {item('financial','coin','Financeiro')}
      {item('reports','chart-bar','Relatórios')}
      {item('proposals','file-invoice','Orçamentos',counts.proposals)}
      {item('projects','layout-kanban','Projetos',counts.projects,'ok')}
      {item('diarios','notebook','Diários')}
      {item('schedule','calendar-event','Cronograma')}

      <div className="sb-item" onClick={onAreaClientes} style={{color:'#E8CFA0'}}>
        <i className="ti ti-presentation-analytics" aria-hidden />
        <span className="sb-label">Área de Clientes</span>
      </div>

      {!isDemo() && <div className="sb-section">Sistema</div>}
      {!isDemo() && item('backup','database-export','Backup & Restore')}
      <div className="sb-section">Cadastros</div>
      {item('clients','users','Clientes')}
      {item('catalog','list-details','Catálogo')}
      {item('stock','box','Estoque',counts.stock_critical)}
      {item('suppliers','truck','Fornecedores')}
      {item('tools','tools','Ferramentas')}
      {item('admins','shield','Admins')}

      {/* Footer — hidden on mobile */}
      <div className="sb-footer" style={{padding:'12px 16px'}}>
        <div style={{fontSize:11,color:'rgba(255,255,255,0.5)',display:'flex',alignItems:'center',gap:6,paddingBottom:10,borderBottom:'1px solid rgba(255,255,255,0.07)'}}>
          <i className="ti ti-user" style={{fontSize:13,flexShrink:0}} aria-hidden />{user?.name}
        </div>
        <button onClick={onLogout} style={{background:'transparent',border:'none',color:'rgba(255,255,255,0.28)',cursor:'pointer',fontSize:11,padding:'10px 0 0 0',fontFamily:'inherit',display:'flex',alignItems:'center',gap:6,marginLeft:0,width:'100%'}}>
          <i className="ti ti-logout" style={{fontSize:13}} aria-hidden />Sair
        </button>
        <div style={{fontSize:9,color:'rgba(255,255,255,0.2)',marginTop:8,fontFamily:'monospace'}}>
          v310 · build 2026-07
        </div>
      </div>
    </div>
  )
}

